export interface CategoryNode {
  name: string;
  slug: string;
  children?: CategoryNode[];
}

export const categoryTree: CategoryNode[] = [
  {
    name: "Gaming Monitor",
    slug: "gaming-monitor",
    children: [
      { name: "Top Gaming Monitor", slug: "top-gaming-monitor" },
      { name: "24 inch", slug: "gaming-24inch" },
      { name: "27 inch", slug: "gaming-27inch" },
      { name: "37.5 inch", slug: "gaming-37-5inch" },
      { name: "23.8 inch", slug: "gaming-23-8inch" },
      { name: "31.5 inch", slug: "gaming-31-5inch" },
      { name: "20 inch", slug: "gaming-20inch" },
      { name: "19 inch", slug: "gaming-19inch" },
      { name: "26 inch", slug: "gaming-26inch" },
      { name: "49 inch", slug: "gaming-49inch" },
      { name: "44 inch", slug: "gaming-44inch" },
      { name: "30 inch", slug: "gaming-30inch" },
      { name: "34 inch", slug: "gaming-34inch" },
      { name: "RTS (Ready to Ship)", slug: "gaming-rts" },
      { name: "1080P 60hz Monitor", slug: "gaming-1080p-60hz" },
      { name: "144hz Monitor", slug: "gaming-144hz" },
      { name: "2K Monitor", slug: "gaming-2k" },
      { name: "4K Monitor", slug: "gaming-4k" },
      { name: "39 inch Monitor", slug: "gaming-39inch" },
      { name: "35 inch Monitor", slug: "gaming-35inch" },
      { name: "32 inch Monitor", slug: "gaming-32inch" },
      { name: "Touch Game Monitor", slug: "gaming-touch" },
    ],
  },
  {
    name: "LCD LED Monitor",
    slug: "lcd-led-monitor",
    children: [
      { name: "RTS", slug: "lcd-rts" },
      { name: "7'' to 42'' Monitor", slug: "lcd-7-42inch" },
      { name: "21.5'' Monitor", slug: "lcd-21-5inch" },
      { name: "24'' Monitor", slug: "lcd-24inch" },
      { name: "27'' Monitor", slug: "lcd-27inch" },
    ],
  },
  {
    name: "Touch Monitors",
    slug: "touch-monitors",
    children: [
      { name: "10.4 inch", slug: "touch-10-4inch" },
      { name: "RTS", slug: "touch-rts" },
      { name: "7 inch Touch Screen", slug: "touch-7inch" },
      { name: "8 inch Touch Screen", slug: "touch-8inch" },
      { name: "10 inch Touch Screen", slug: "touch-10inch" },
      { name: "12 inch Touch Screen", slug: "touch-12inch" },
      { name: "13.3 inch Touch Screen", slug: "touch-13-3inch" },
      { name: "14 inch Touch Screen", slug: "touch-14inch" },
      { name: "15 inch Touch Screen", slug: "touch-15inch" },
      { name: "15.6 inch Touch Screen", slug: "touch-15-6inch" },
      { name: "17 inch Touch Screen", slug: "touch-17inch" },
      { name: "18.5 inch Touch Screen", slug: "touch-18-5inch" },
      { name: "19 inch Touch Screen", slug: "touch-19inch" },
      { name: "20-32 inch Touch Screen", slug: "touch-20-32inch" },
      { name: "42-84 inch Touch Screen", slug: "touch-42-84inch" },
    ],
  },
  {
    name: "CCTV Monitor",
    slug: "cctv-monitor",
    children: [
      { name: "23'' CCTV Monitor", slug: "cctv-23inch" },
      { name: "RTS", slug: "cctv-rts" },
      { name: "3.5'' to 55'' CCTV Monitor", slug: "cctv-3-5-55inch" },
      { name: "32''-55'' CCTV Monitor", slug: "cctv-32-55inch" },
    ],
  },
  {
    name: "Creative LED Display",
    slug: "creative-led-display",
    children: [
      { name: "Triangle LED Display", slug: "led-triangle" },
      { name: "Cylinder LED Display", slug: "led-cylinder" },
      { name: "Can LED Display", slug: "led-can" },
      { name: "Tree LED Display", slug: "led-tree" },
      { name: "Logo LED Display", slug: "led-logo" },
      { name: "Sphere LED Display", slug: "led-sphere" },
      { name: "Cube LED Display", slug: "led-cube" },
      { name: "Circular LED Display", slug: "led-circular" },
      { name: "Dome LED Display", slug: "led-dome" },
    ],
  },
  { name: "POS PC", slug: "pos-pc" },
  {
    name: "Tablet PC",
    slug: "tablet-pc",
    children: [
      { name: "24 inch", slug: "tablet-24inch" },
      { name: "Rugged Tablet PC", slug: "tablet-rugged" },
      { name: "RTS", slug: "tablet-rts" },
      { name: "7-27 inch Tablet PC", slug: "tablet-7-27inch" },
      { name: "10.1 inch Tablet PC", slug: "tablet-10-1inch" },
      { name: "15.6 inch Tablet PC", slug: "tablet-15-6inch" },
    ],
  },
  { name: "Regular LED Display", slug: "regular-led-display" },
  { name: "Digital Photo Frame", slug: "digital-photo-frame" },
  { name: "Open Frame Monitor", slug: "open-frame-monitor" },
  { name: "WIFI All-in-one PC", slug: "wifi-all-in-one-pc" },
  { name: "Car Monitors", slug: "car-monitors" },
  { name: "Android Advertising Media Player", slug: "android-advertising-player" },
  { name: "Electronic Interactive Whiteboard", slug: "electronic-whiteboard" },
  { name: "LCD/LED TV with 4K", slug: "lcd-led-tv-4k" },
  { name: "Laptop", slug: "laptop" },
  { name: "DDP Terms Product", slug: "ddp-terms-product" },
  { name: "Hot Sale Product", slug: "hot-sale-product" },
  { name: "New Product", slug: "new-product" },
  { name: "Other", slug: "other" },
];
